### ISSUE TITLE
Consider contributing to PDE

### ISSUE THREAD

**Issue by mickaelistria** [secondfiddle/pep-tools#11]
Would you consider contributing your extensions directly to PDE? I believe they'd make sense there.

**Comment by edscadding** [comment]
Absolutely, if the PDE devs wanted it and it could be made to fit in with existing code.  I think the Feature Explorer and product-validation functionality could fit well; the other parts of PEP Tools, less so!

**Comment by mickaelistria** [comment]
I believe the (very few) active PDE contributors would welcome this feature. The procedure is simply to start by opening a bug via http://bugs.eclipse.org, then attach a patch via Gerrit https://git.eclipse.org/r/#/admin/projects/pde/eclipse.pde.ui .

**Comment by edscadding** [comment]
Ok, I'll look into it then.  Thanks for the suggestion and information.

**Comment by edscadding** [comment]
I've opened a bug, as suggested: https://bugs.eclipse.org/bugs/show_bug.cgi?id=490035.

**Comment by edscadding** [comment]
Feature Explorer contribution now in progress, so closing :)
