### ISSUE TITLE
Adding a source folder to the product editor in Standard

### ISSUE THREAD

**Issue by vogella** [secondfiddle/pep-tools#16]
I noticed you have an extension for the product editor to also contain a source tab. Are you interested in contributing this to PDE? Would be nice to have that in standard.

**Comment by edscadding** [comment]
Hi Lars, thanks for your interest! Yes, I would be happy to contribute it. Are you interested in any other features? Specifically the [product nature/builder](https://github.com/secondfiddle/pep-tools#product-validation) (for eager product validation) or [feature explorer](https://github.com/secondfiddle/pep-tools#feature-explorer) (to aid feature visualisation and refactoring)?

What should my next step be? I raised a PDE UI enhancement bug on the Eclipse Bugzilla regarding [integration of PEP Tools features](https://bugs.eclipse.org/bugs/show_bug.cgi?id=490035) a few years ago, if that's helpful.

**Comment by vogella** [comment]
Feature view is also a very interesting feature. Maybe you can cooperate with @wimjongman on this? Currently we are discussion his contribution from https://github.com/wimjongman/featureexplorer in https://bugs.eclipse.org/bugs/show_bug.cgi?id=543217

**Comment by vogella** [comment]
For the source tab, I suggest we use https://bugs.eclipse.org/bugs/show_bug.cgi?id=96894 and use the generic editor (which is our preferred tool for new text features)

**Comment by edscadding** [comment]
Ok, I'll start there, and move further discussion over to Bugzilla – thanks Lars!

**Comment by edscadding** [comment]
Feature Explorer contribution now in progress, and product editor source tab contributed by someone else, so closing :)

**Comment by vogella** [comment]
Thanks, Ed.

Ed Scadding <notifications@github.com> schrieb am Sa., 17. Aug. 2019, 19:54:
